# Generated by Django 5.1.4 on 2024-12-06 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_candidate_date_of_birth'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='candidate',
            options={},
        ),
        migrations.AlterModelManagers(
            name='candidate',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='admin',
            name='password',
        ),
        migrations.RemoveField(
            model_name='admin',
            name='username',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='email',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='password',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='user_permissions',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='username',
        ),
        migrations.AddField(
            model_name='admin',
            name='date_of_birth',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='admin',
            name='full_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='admin',
            name='phone_number',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='phone_number',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
