# Generated by Django 4.2.17 on 2024-12-21 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_candidate_options_alter_candidate_managers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='access_end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='access_start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
