# Generated by Django 4.2.17 on 2025-01-08 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('marks', models.IntegerField()),
                ('max_selection', models.IntegerField(default=1)),
                ('show_num_selection', models.BooleanField(default=False)),
                ('question_type', models.CharField(choices=[('single', 'Multiple Choice (Single Answer)'), ('multiple', 'Multiple Choice (Multiple Answers)'), ('text', 'Text Answer')], default='single', max_length=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='questions/')),
                ('answer_text', models.TextField(blank=True, null=True)),
                ('duration', models.DurationField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='QuestionOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('is_correct', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('total_marks', models.IntegerField()),
                ('max_attempts', models.IntegerField(default=1)),
                ('duration', models.DurationField(blank=True, null=True)),
                ('counterType', models.CharField(choices=[('test_duration', 'Duration counter by overall test'), ('question_duration', 'Every question has its duration')], default='test_duration', max_length=100)),
            ],
        ),
    ]
