# Generated by Django 5.1.4 on 2024-12-05 13:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0002_question_questionoption'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='questions/'),
        ),
        migrations.AddField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('single', 'Multiple Choice (Single Answer)'), ('multiple', 'Multiple Choice (Multiple Answers)'), ('text', 'Text Answer')], default='single', max_length=10),
        ),
        migrations.AlterField(
            model_name='questionoption',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='exams.question'),
        ),
        migrations.AlterField(
            model_name='questionoption',
            name='text',
            field=models.TextField(),
        ),
    ]
