# Generated by Django 5.1.4 on 2024-12-11 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0004_alter_question_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='text_answer',
            field=models.TextField(blank=True, null=True),
        ),
    ]
