# Generated by Django 5.1.4 on 2024-12-11 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0005_question_text_answer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='text_answer',
        ),
    ]
