# Generated by Django 5.1.4 on 2024-12-11 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0006_remove_question_text_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='answer_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
