# Generated by Django 5.1.4 on 2024-12-18 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0007_question_answer_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='company',
        ),
        migrations.AddField(
            model_name='test',
            name='max_attempts',
            field=models.IntegerField(default=1),
        ),
    ]
