# Generated by Django 5.1.4 on 2024-12-18 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0008_remove_test_company_test_max_attempts'),
        ('users', '0004_alter_candidate_options_alter_candidate_managers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='candidates',
            field=models.ManyToManyField(related_name='tests', to='users.candidate'),
        ),
    ]
