# Generated by Django 5.1.4 on 2024-12-18 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0009_test_candidates'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='duration',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='test',
            name='counterType',
            field=models.CharField(choices=[('test_duration', 'Duration counter by overall test'), ('question_duration', 'Every question has its duration')], default='test_duration', max_length=100),
        ),
        migrations.AddField(
            model_name='test',
            name='duration',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
