# Generated by Django 4.2.17 on 2024-12-21 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0010_question_duration_test_countertype_test_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='max_selection',
            field=models.IntegerField(default=1),
        ),
    ]
