# Generated by Django 4.2.17 on 2024-12-21 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0011_question_max_selection'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='show_num_selection',
            field=models.BooleanField(default=False),
        ),
    ]
