# Generated by Django 5.1.4 on 2024-12-18 20:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0007_question_answer_text'),
        ('videos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MonitoringLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('activity_type', models.CharField(max_length=50)),
                ('data', models.TextField()),
                ('screenshot', models.ImageField(blank=True, null=True, upload_to='monitoring_screenshots/')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exams.test')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
