# Generated by Django 5.1.5 on 2025-01-18 11:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monitoringlog',
            name='user',
        ),
        migrations.AddField(
            model_name='monitoringlog',
            name='candidate',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='users.candidate'),
        ),
    ]
