# Generated by Django 5.1.5 on 2025-02-08 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0002_remove_monitoringlog_user_monitoringlog_candidate'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitoringlog',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
    ]
